Repository elsafluss/rancid-tomatillos, pull requests merged in 2021-02, with the labels that each got.

#5 Feature html start
  .eslintcache
  public/index.html
  src/App.css
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.scss
  src/CardContainer/CardContainer.css
  src/CardContainer/CardContainer.js
  src/Header/Header.css
  src/Header/Header.js
  src/index.js
  src/movieData.js
Labels: Data, Display, enhancement

#12 Feature display modal
  .eslintcache
  package-lock.json
  package.json
  public/index.html
  src/App/App.js
  src/App/App.scss
  src/Card/Card.js
  src/CardContainer/CardContainer.js
  src/CardContainer/CardContainer.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/index.js
  src/index.scss
  src/reportWebVitals.js
  src/styles/_mixins.scss
  src/styles/_variables.scss
Labels: Data, Display, enhancement

#13 Feature display modal
  .eslintcache
  src/App/App.js
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/CardContainer/CardContainer.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Modal/Modal.js
  src/index.scss
  src/util.js
Labels: API, Data, Display, test

#14 Display movie data on modal and design modal.
  .eslintcache
  .gitignore
  src/App/App.js
  src/App/App.scss
  src/Card/Card.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/index.scss
Labels: Display

#18 Feature search
  .eslintcache
  src/App/App.js
  src/Form/Form.js
  src/Form/Form.scss
  src/Header/Header.js
  src/Modal/Modal.js
Labels: Data, Display, enhancement

#22 Router setup
  .eslintcache
  cypress.json
  cypress/.eslintrc.json
  cypress/fixtures/example.json
  cypress/integration/homepage_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/CardContainer/CardContainer.js
  src/CardContainer/CardContainer.scss
  src/Form/Form.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/background.png
  src/index.js
  src/index.scss
Labels: Display, enhancement

#23 Add conditional rendering in modal for budget and revenue data.
  .eslintcache
  src/Modal/Modal.js
Labels: Display

#25 Feature/add proptypes
  .eslintcache
  src/Card/Card.js
  src/CardContainer/CardContainer.js
  src/Form/Form.js
  src/Header/Header.js
  src/Modal/Modal.js
  src/index.js
Labels: Data

#27 Add link to home page to title in header.
  src/Header/Header.js
Labels: Display, enhancement

#31 Feature styling
  .eslintcache
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/CardContainer/CardContainer.scss
  src/Error/Error.js
  src/Error/Error.scss
  src/Form/Form.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Loading/Loading.js
  src/Loading/Loading.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/index.scss
  src/styles/_variables.scss
Labels: Display, enhancement

#33 Feature/mobile responsiveness
  .eslintcache
  cypress/integration/async_spec.js
  cypress/integration/homepage_spec.js
  src/App/App.js
  src/App/App.scss
  src/Card/Card.scss
  src/CardContainer/CardContainer.scss
  src/Error/Error.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/index.scss
Labels: Display

#35 Pass lighthouse accessibility audit.
  src/Card/Card.js
  src/Card/Card.scss
  src/CardContainer/CardContainer.js
  src/Form/Form.js
Labels: Display, enhancement

#36 Finish drying SCSS
  .eslintcache
  src/App/App.js
  src/App/App.scss
  src/Card/Card.scss
  src/Error/Error.scss
  src/Form/Form.js
  src/Form/Form.scss
  src/Header/Header.scss
  src/Modal/Modal.scss
  src/index.scss
  src/styles/_mixins.scss
Labels: Display

#37 Cleanup
  .eslintcache
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Error/Error.js
  src/Header/Header.js
  src/Loading/Loading.js
  src/Loading/Loading.scss
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/background.png
  src/logo.svg
  src/setupTests.js
Labels: enhancement

#39 Change home page link in tests to match deployed site.
  .eslintcache
  cypress/integration/async_spec.js
  cypress/integration/homepage_spec.js
  cypress/integration/modal_spec.js
Labels: bug, test
